### ISSUE TITLE
python 3.5 issues

### ISSUE THREAD

**Issue by harmv** [piglei/uwsgi-sloth#12]
There is already #10, I couldn't re-open, so I filed a new ticket instead.

When running on python 3.5 I get errors

```
(v) harm@sensor1:~/uwsgi-sloth$ uwsgi-sloth start -c josene.conf 
[2019-02-28 10:53:29,072] uwsgi_sloth INFO: Start from last savepoint, last_log_datetime: 2019-02-28 10:48:29.071966
[2019-02-28 10:53:35,884] uwsgi_sloth INFO: Rendering HTML file /home/harm/uwsgi-sloth/html/html/latest_5mins.html...
[2019-02-28 10:53:35,916] uwsgi_sloth INFO: Rendering HTML file /home/harm/uwsgi-sloth/html/html/day_2019-02-28.html...
Traceback (most recent call last):
  File "/home/harm/uwsgi-sloth/v/bin/uwsgi-sloth", line 32, in <module>
    main()
  File "/home/harm/uwsgi-sloth/v/bin/uwsgi-sloth", line 25, in main
    args.func(args)
  File "/home/harm/uwsgi-sloth/v/lib/python3.5/site-packages/uwsgi_sloth/commands/start.py", line 118, in start
    day_requests_data.save()
  File "/home/harm/uwsgi-sloth/v/lib/python3.5/site-packages/uwsgi_sloth/models.py", line 48, in save
    pickle.dump(self.data, fp)
TypeError: write() argument must be str, not bytes
```

When changing models.py::RequestsData  to open() as  'rb' and 'wb' this crash disappears, but then I get

```
[2019-02-28 10:56:56,919] uwsgi_sloth INFO: Start from last savepoint, last_log_datetime: 2019-02-28 10:51:56.919301
[2019-02-28 10:57:03,777] uwsgi_sloth INFO: Rendering HTML file /home/harm/uwsgi-sloth/html/html/latest_5mins.html...
[2019-02-28 10:57:03,812] uwsgi_sloth INFO: Rendering HTML file /home/harm/uwsgi-sloth/html/html/day_2019-02-28.html...
Traceback (most recent call last):
  File "/home/harm/uwsgi-sloth/v/bin/uwsgi-sloth", line 32, in <module>
    main()
  File "/home/harm/uwsgi-sloth/v/bin/uwsgi-sloth", line 25, in main
    args.func(args)
  File "/home/harm/uwsgi-sloth/v/lib/python3.5/site-packages/uwsgi_sloth/commands/start.py", line 111, in start
    for date in analyzer.data.keys():
RuntimeError: dictionary changed size during iteration
```

last crash might not be a python3.5 issue, but first crash is I think.

### version
uwsgi-sloth==3.0.1

**Comment by piglei** [comment]
Hi, @harmv sorry for the inconvenience, I just release a new version 3.0.2 to fix the problem you reported. Please give it a try.

This project was not very active for a long time and definitely needs more unit tests, if you encounter any other problems, please let me know.

Thank you.
